### ISSUE TITLE
Abkürzungsverzeichnis

### ISSUE THREAD

**Issue by not-a-feature** [mircohaug/MA#3]
- manche Abkürzungen beginnen mit einem kleinen, mache mit einem großen Buchstaben. Einheitlich wäre es schöner.

- mit `\begin{tabbing} .... \end{tabbing}` sollte es möglich sein, den Abstand zwischen Abkürzung und Erklärung zu vereinheitlichen

**Comment by mircohaug** [comment]
The glossaries package already provides the style `super` which does exactly this. Fixed with 64dfd389af3548be23a06b649637a8cca110a41c
